interface configurationListType {
  name: string
  title: string
  description: string
  inputType: 'edit' | 'text' | 'password' | 'select' | 'number' | 'email'
  defaultValue: string | boolean
  options?: { label: string; value: string }[]
  required: boolean
}
export const configurationList: configurationListType[] = [
  {
    name: 'fromAddress',
    title: 'From Address',
    description:
      'The email address that appears in the <b>From</b> header line in email messages generated by PingFederate. The address must be in valid format but need not be set up on your system.',
    inputType: 'text',
    defaultValue: 'Support MFA<vihardevalla@gmail.com>',
    required: true
  },
  {
    name: 'emailServer',
    title: 'Email Server',
    description: 'The IP address or hostname of your email server.',
    inputType: 'text',
    defaultValue: 'smtp.gmail.com',
    required: true
  },
  {
    name: 'emailPort',
    title: 'Email Port',
    description: 'The SMTP port on your email server. The default value is 25.',
    inputType: 'number',
    defaultValue: '25',
    required: true
  },
  {
    name: 'Encryption Method',
    title: 'Encryption Method',
    description:
      'Select None (the default) to establish an unencrypted connection to the email server at the SMTP port. Select SSL/TLS to establish a secure connection to the email server at the SMTPS port. Select STARTTLS to establish an unencrypted connection to the email server at the SMTP port and initiate a secure channel afterward.',
    inputType: 'select',
    defaultValue: 'STARTTLS',
    options: [
      { label: 'None', value: '' },
      { label: 'STARTTLS', value: 'STARTTLS' },
      { label: 'SSL', value: 'SSL' }
    ],
    required: true
  },
  {
    name: 'emailOAuth',
    title: 'Email OAuth',
    description: 'Toggle between SMTP and OAuth for sending emails',
    inputType: 'select',
    defaultValue: 'SMTP',
    options: [
      { label: 'Custom OAuth', value: 'Custom OAuth' },
      { label: 'Microsoft 365', value: 'Microsoft 365' },
      { label: 'SMTP', value: 'SMTP' }
    ],
    required: true
  },
  {
    name: 'username',
    title: 'Username',
    description: 'Authorized email account.',
    inputType: 'text',
    defaultValue: 'vihardevalla@gmail.com',
    required: true
  },
  {
    name: 'password',
    title: 'Password',
    description:
      'Enter an email address the PingFederate should use to verify connectivity with the configured email server.',
    inputType: 'password',
    defaultValue: '12345',
    required: true
  },
  {
    name: 'header',
    title: 'Header',
    description: 'The header of the email message.',
    inputType: 'edit',
    defaultValue: '',
    required: false
  },
  {
    name: 'footer',
    title: 'Footer',
    description: 'The footer of the email message.',
    inputType: 'edit',
    defaultValue: '',
    required: false
  }
]
